spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center
    username: root
    password: 111111
  session:
    timeout: 86400  #超时时间 1day = 86400s